version: '3'
services:
  server:
    build: ./server
    container_name: grpc-server
    ports:
      - "50051:50051"

  client:
    build: ./client
    container_name: grpc-client
    depends_on:
      - server