apiVersion: v1
kind: Service
metadata:
  name: so1-service-nodeport
spec:
  selector:
    app: so1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30081
  type: NodePort
