version: "3"

services:
  server:
    image: MI_IP.nip.io/ht05-grpc/grpc-server
    container_name: grpc-server
    ports:
      - "50051:50051"

  client:
    image: MI_IP.nip.io/ht05-grpc/grpc-client
    container_name: grpc-client
    depends_on:
      - server
